// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFL1yCLSvFaY7fjbLF0GAfKpScV0DJhQU',
    appId: '1:178555985064:web:425e52eb2f40e386e3f69d',
    messagingSenderId: '178555985064',
    projectId: 'onward-f2e6e',
    authDomain: 'onward-f2e6e.firebaseapp.com',
    storageBucket: 'onward-f2e6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiHZ0EgQMJiuYUekoNHKEDBdyx8rg1M9o',
    appId: '1:178555985064:android:1d9dc4de0e54b6a9e3f69d',
    messagingSenderId: '178555985064',
    projectId: 'onward-f2e6e',
    storageBucket: 'onward-f2e6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDluQZ0pZSTUMayv5-9Ckt2SiH0oE5gc00',
    appId: '1:178555985064:ios:062f1ed92d78a7c5e3f69d',
    messagingSenderId: '178555985064',
    projectId: 'onward-f2e6e',
    storageBucket: 'onward-f2e6e.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDluQZ0pZSTUMayv5-9Ckt2SiH0oE5gc00',
    appId: '1:178555985064:ios:062f1ed92d78a7c5e3f69d',
    messagingSenderId: '178555985064',
    projectId: 'onward-f2e6e',
    storageBucket: 'onward-f2e6e.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFL1yCLSvFaY7fjbLF0GAfKpScV0DJhQU',
    appId: '1:178555985064:web:9e42c5a1eb524a4de3f69d',
    messagingSenderId: '178555985064',
    projectId: 'onward-f2e6e',
    authDomain: 'onward-f2e6e.firebaseapp.com',
    storageBucket: 'onward-f2e6e.firebasestorage.app',
  );
}
